/** THIS FILE IS AUTOMATICALLY GENERATED FROM home/xananax/projects/gdquest/build-scripts/products-creator/writeSiteData.js **/
/** DO NOT TOUCH OR MODIFY IT IN ANY WAY **/

/**
 * List of products available on Stripe
 */
export const products: Product[] = [
  {
    product: {
      name: 'Best Course',
      description: 'A very cool course',
      id: 'prod_L5iETLqj8e4bGa'
    },
    price: {
      currency: 'usd',
      unit_amount: 1000,
      recurring: {
        interval: 'month'
      },
      id: 'price_1KPWo8Ka4Qks6fcmwdTlL7dT'
    },
    includes: ['How to make games', 'Paying money', '200 fresh random numbers']
  },
  {
    product: {
      name: 'Infinite Course',
      description: 'Its infinite',
      id: 'prod_L5iEoS5PvvDbfi'
    },
    price: {
      currency: 'usd',
      unit_amount: 1500,
      recurring: {
        interval: 'month'
      },
      id: 'price_1KPWo8Ka4Qks6fcmpLkLlRZ6'
    },
    includes: [
      'All of the best course',
      'A bestest course',
      'Infinite course',
      'Potatoes',
      'Pay more'
    ]
  }
]
